import type { GlossaryTerm } from './types'

export const GLOSSARY: GlossaryTerm[] = [
  { id: 'annual-cohort', term: 'Annual cohort', definition: 'The rule that a group may only contain contracts issued no more than one year apart.', concept: 'level-of-aggregation' },
  { id: 'contract-boundary-term', term: 'Contract boundary', definition: 'The limit beyond which future cash flows belong to a new contract, because the insurer can reprice for the risk.', concept: 'contract-boundary' },
  { id: 'coverage-period', term: 'Coverage period', definition: 'The period during which the insurer provides insurance services under the contracts in a group.' },
  { id: 'coverage-unit', term: 'Coverage units', definition: 'A measure of the insurance service provided in each period, used to release the CSM.', concept: 'coverage-units' },
  { id: 'csm-term', term: 'Contractual service margin', abbr: 'CSM', definition: 'The unearned profit in a group of contracts, released as services are provided.', concept: 'csm' },
  { id: 'experience-adjustment', term: 'Experience adjustment', definition: 'The difference between expected and actual cash flows for the current or past period. It goes to profit or loss, not the CSM.' },
  { id: 'fcf', term: 'Fulfilment cash flows', abbr: 'FCF', definition: 'Discounted, probability-weighted future cash flows plus the risk adjustment.', concept: 'fulfilment-cash-flows' },
  { id: 'gmm-term', term: 'General Measurement Model', abbr: 'GMM', definition: 'The default IFRS 17 model: fulfilment cash flows plus CSM. Also called the building block approach.', concept: 'gmm' },
  { id: 'group', term: 'Group of insurance contracts', definition: 'The unit of account in IFRS 17: a portfolio split by profitability and annual cohort.', concept: 'level-of-aggregation' },
  { id: 'iacf', term: 'Insurance acquisition cash flows', definition: 'Costs of selling, underwriting and starting a group of contracts, such as commissions.', concept: 'acquisition-cash-flows' },
  { id: 'insurance-contract-term', term: 'Insurance contract', definition: 'A contract under which one party accepts significant insurance risk from another by agreeing to compensate them if a specified uncertain future event adversely affects them.', concept: 'insurance-contract' },
  { id: 'ifie', term: 'Insurance finance income or expenses', abbr: 'IFIE', definition: 'The change in insurance liabilities arising from the time value of money and financial risk.', concept: 'insurance-finance' },
  { id: 'insurance-revenue-term', term: 'Insurance revenue', definition: 'Consideration for insurance services provided in the period, excluding investment components.', concept: 'insurance-revenue' },
  { id: 'isr', term: 'Insurance service result', definition: 'Insurance revenue less insurance service expenses.' },
  { id: 'ise', term: 'Insurance service expenses', definition: 'Incurred claims and expenses, amortisation of acquisition cash flows, and losses and reversals on onerous groups.' },
  { id: 'investment-component', term: 'Investment component', definition: 'Amounts repaid to a policyholder in all circumstances, whether or not an insured event occurs. Excluded from revenue and claims expenses.' },
  { id: 'lic-term', term: 'Liability for incurred claims', abbr: 'LIC', definition: 'The obligation to pay for insured events that have already occurred.', concept: 'lic' },
  { id: 'lrc-term', term: 'Liability for remaining coverage', abbr: 'LRC', definition: 'The obligation to provide insurance cover in the future.', concept: 'lrc' },
  { id: 'locked-in-rate', term: 'Locked-in discount rate', definition: 'The discount rate determined at initial recognition of a group, used to accrete interest on the CSM.', concept: 'discounting' },
  { id: 'loss-component-term', term: 'Loss component', definition: 'A memo account within the LRC tracking losses recognised on onerous groups.', concept: 'loss-component' },
  { id: 'oci-option', term: 'OCI option', definition: 'A policy choice to split insurance finance income or expenses between profit or loss and other comprehensive income.', concept: 'insurance-finance' },
  { id: 'onerous', term: 'Onerous contract', definition: 'A contract or group whose expected outflows, including the risk adjustment, exceed expected inflows.', concept: 'onerous-contracts' },
  { id: 'paa-term', term: 'Premium Allocation Approach', abbr: 'PAA', definition: 'An optional simplification of the LRC for short-duration contracts.', concept: 'paa' },
  { id: 'portfolio', term: 'Portfolio', definition: 'Insurance contracts subject to similar risks and managed together.', concept: 'level-of-aggregation' },
  { id: 'present-value', term: 'Present value', abbr: 'PV', definition: 'The value today of an amount paid or received in the future, after discounting.', concept: 'discounting' },
  { id: 'ra', term: 'Risk adjustment for non-financial risk', abbr: 'RA', definition: 'The compensation required for bearing uncertainty from non-financial risk.', concept: 'risk-adjustment' },
  { id: 'reinsurance-contract-held', term: 'Reinsurance contract held', definition: 'A contract under which the insurer transfers insurance risk to a reinsurer. Measured separately from the underlying contracts it covers.', concept: 'reinsurance-held' },
  { id: 'underlying-items', term: 'Underlying items', definition: 'The assets or fund that determine amounts payable to policyholders in direct participating contracts.', concept: 'vfa' },
  { id: 'vfa-term', term: 'Variable Fee Approach', abbr: 'VFA', definition: 'The modified GMM for contracts with direct participation features.', concept: 'vfa' },
  { id: 'iasb', term: 'IASB', definition: 'International Accounting Standards Board, the independent body that issues IFRS Accounting Standards.', concept: 'what-is-ifrs' },
  { id: 'debit-credit', term: 'Debit and credit', definition: 'The two sides of every journal entry. Assets and expenses increase with debits; liabilities, equity and income with credits.', concept: 'double-entry' },
  { id: 'subledger', term: 'Subledger', definition: 'A detailed ledger, such as an IFRS 17 engine, that calculates and posts summarised entries to the general ledger.', concept: 'tagetik-journals' },
  { id: 'tagetik', term: 'CCH Tagetik', definition: 'A corporate performance management platform from Wolters Kluwer, with a solution for IFRS 17.', concept: 'tagetik-overview' },
  { id: 'conceptual-framework-term', term: 'Conceptual Framework', definition: 'The IASB document that defines the elements of financial statements and the concepts for recognising and measuring them. It is not a Standard and does not override one.', concept: 'conceptual-framework' },
  { id: 'unit-of-account', term: 'Unit of account', definition: 'The right, obligation or group of them to which recognition and measurement requirements are applied. In IFRS 17 it is the group of insurance contracts.', concept: 'conceptual-framework' },
  { id: 'fulfilment-value', term: 'Fulfilment value', definition: 'A Conceptual Framework current value measure for liabilities: the present value of the resources an entity expects to be obliged to transfer as it fulfils the liability.', concept: 'conceptual-framework' },
  { id: 'fair-value', term: 'Fair value', definition: 'The price that would be received to sell an asset or paid to transfer a liability in an orderly transaction between market participants at the measurement date (IFRS 13).', concept: 'key-standards' },
  { id: 'accounting-mismatch', term: 'Accounting mismatch', definition: 'Volatility that arises when related assets and liabilities are measured on different bases or their changes are recognised in different places, such as profit or loss versus OCI.', concept: 'key-standards' },
  { id: 'fvoci', term: 'Fair value through other comprehensive income', abbr: 'FVOCI', definition: 'An IFRS 9 measurement category in which a financial asset is carried at fair value with changes recognised in OCI. For debt instruments, interest and credit losses still go to profit or loss.', concept: 'key-standards' },
  { id: 'loss-recovery-component', term: 'Loss-recovery component', definition: 'A component of the asset for remaining coverage of a group of reinsurance contracts held that tracks recoveries of losses recognised on onerous underlying contracts (IFRS 17.66A–66B, B119C–B119F).', concept: 'reinsurance-held' },
  { id: 'non-performance-risk', term: 'Non-performance risk', definition: 'The risk that a party will not fulfil its obligation. Included for the reinsurer when measuring reinsurance held; excluded for the entity’s own contracts issued.', concept: 'reinsurance-held' },
  { id: 'ceding-commission', term: 'Ceding commission', definition: 'An amount the reinsurer pays to the cedant. If not contingent on claims, it reduces the reinsurance premiums paid; if contingent on claims, it is part of the amounts recovered.', concept: 'reinsurance-held' },
  { id: 'quota-share', term: 'Quota share', definition: 'Proportional reinsurance in which the reinsurer takes a fixed percentage of premiums and claims of the covered business.', concept: 'reinsurance-held' },
  { id: 'analysis-of-change', term: 'Analysis of change', abbr: 'AoC', definition: 'A step-by-step attribution of the movement in a measure, such as the CSM or fulfilment cash flows, to causes like new business, interest, assumption changes and experience.', concept: 'operating-ifrs17' },
  { id: 'data-dictionary', term: 'Data dictionary', definition: 'The agreed definition of every field exchanged between systems or teams: meaning, grain, format, sign convention and owner.', concept: 'operating-ifrs17' },
  { id: 'dimension', term: 'Dimension', definition: 'An axis along which data is stored and analysed in a multidimensional platform, such as entity, account, period or scenario.', concept: 'tagetik-platform' },
  { id: 'scenario', term: 'Scenario', definition: 'In a performance management platform, a separate version of the data, such as actual, budget or forecast, or projected versus actual cash flows.', concept: 'tagetik-platform' },
  { id: 'ifrs-18', term: 'IFRS 18', definition: 'Presentation and Disclosure in Financial Statements: replaces IAS 1 for annual periods beginning on or after 1 January 2027, introducing defined subtotals and income and expense categories.', concept: 'financial-statements' },
]
